### register
POST http://localhost:8080/api/apps
Content-Type: application/x-www-form-urlencoded

app=go-scratchpad&gitUrl=git@github.com:JackKCWong/go-scratchpad.git


### register
POST http://localhost:8080/api/apps
Content-Type: application/json

{
  "app": "hello-world",
  "gitUrl": "git@github.com:JackKCWong/go-runner-hello-world.git"
}

### get health
GET http://localhost:8080/api/health

### get hello
GET http://localhost:8080/nihao-shijie/nihao

### deploy
PUT http://localhost:8080/api/nihao-shijie
Content-Type: application/x-www-form-urlencoded

action=deploy

### restart 
PUT http://localhost:8080/api/nihao-shijie
Content-Type: application/x-www-form-urlencoded

action=restart

### delete 
DELETE http://localhost:8080/api/nihao-shijie

### delete 
DELETE http://localhost:8080/api/hello-world

### delete
DELETE http://localhost:8080/api/go-runner-hello-world
