### register
POST http://localhost:8080/api/apps
Content-Type: application/json

{
  "app": "nihao-shijie",
  "gitUrl": "./examples/go-runner-nihao-shijie"
}

### get health
GET http://localhost:8080/api/health

### get hello
GET http://localhost:8080/nihao-shijie/nihao

### deploy
PUT http://localhost:8080/api/nihao-shijie
Content-Type: application/json

{
  "action": "deploy"
}

### restart 
PUT http://localhost:8080/api/nihao-shijie
Content-Type: application/json

{
  "action": "restart"
}


### delete 
DELETE http://localhost:8080/api/nihao-shijie
